canonical/jaas.ai

requirements.txt
templates/404.html
templates/_layout.html
templates/big-data.html
templates/community.html
templates/community/cards.html
templates/community/charmers.html
templates/community/partners.html
templates/containers.html
templates/experts.html
templates/experts/spicule.html
templates/experts/tengu.html
templates/how-it-works.html
templates/index.html
templates/jaas.html
templates/kubernetes.html
templates/openstack.html
templates/store.html
webapp/app.py
yarn.lock

QA
--
`./run` and go to http://localhost:8029. Click around, check all links work.

Add all pages; link to jujucharms for user/charm pages

---

webapp/app.py
webapp/handlers.py
webapp/jaasai/views.py
webapp/routing.py
webapp/store/views.py

Fix python linters
Make sure project still works ;P

Fix linters

---

.travis.yml
package.json
webapp/app.py
webapp/jaasai/views.py
webapp/store/views.py

- Add travis.yml
- Add `python-lint` to have minimal test on the app
- Fix some linting problems
Make sure job works well

Add travis.yml and python linters

---

static/js/accordion.js
static/js/app/treefilelist.js
static/js/cli-typer.js
static/js/treefilelist.js
templates/_layout.html
templates/jaasai/index.html
templates/store/bundle-details.html
templates/store/charm-details.html
webapp/store/models.py
webapp/store/views.py

Build the bundle details page
- Go to http://0.0.0.0:8029/openstack-base check it loads and looks good compared to live
- Check out a few bundle URLs
- Check out different versions like: http://0.0.0.0:8029/openstack-base/54
Fixes https://github.com/ubuntudesign/juju-squad/issues/349

Bundle details

---

static/sass/styles-vanilla-v1.scss
templates/jaasai/index.html

- Update homepage to use the latest approved logos for the logo cloud
- Update the 'Join the movement' section to reflect jujucharms.com
- Pull feature branch
- Run `./run`
- Check homepage at http://0.0.0.0:8029/
- Ensure no broken images

Update outdated homepage sections

---

templates/jaasai/how-it-works.html

Fix broken link on /how-it-works
- Pull feature branch
- Run `./run`
- Go to /how-it-works
- Scroll to link 'Visit the docs to get started with JAAS'
- Verify you end up on the correct docs page
Fixes #14

Fix broken link on /how-it-works

---

.travis.yml

..as we now use CircleCI instead.
- Verify CircleCI test and pass on this PR.
- Verify Travis tests no longer appear

Remove Travis config

---

templates/_layout.html
templates/jaasai/community.html
templates/store/bundle-details.html
templates/store/charm-details.html

Google+ is now dead - may Tim Berners-Lee have mercy on its soul.

Remove Google+

---

package.json
yarn.lock

Fixes #49 
- `./run`
- `yarn audit`
- Does it build successfully? 
- Does it look correct?

Updated resolutions values in package.json to upgrade sub dependenciess lodash, braces, and minimatch that have vulnerabilities.

---

templates/_layout.html
webapp/jaasai/views.py

- Display the /jaas page content at /getting-started
- Pull code
- Click the Getting started link in the header, it should show a page of content.
- Fixes: #68.

Add /getting-started page

---

package.json
requirements.txt
tests/store/test_views.py

- Add basic tests for the store views.
- Pull code
- Run `./run test`
- The tests should pass

Add basic view tests

---

templates/store/search.html
tests/store/test_views.py
webapp/store/views.py

[List of work items including drive-bys]
- Pull code
- Do a search where there are no results. You should see an appropriate message.
- Fixes: #59.

Show message when there are no results

---

static/js/src/app.js
static/js/src/modules/search-panel.js
static/sass/custom/_search-panel.scss
static/sass/styles.scss
templates/_layout.html
webapp/app.py

- Add a dropdown panel when the search box is clicked.
- Pull code
- Click inside the search box in the header. The panel should open.

Add search dropdown panel

---

.circleci/config.yml

- Add a python tests job to the CI runner.

Add the python test job to Circle CI

---

tests/jaasai/test_views.py
tests/store/test_views.py
webapp/store/views.py

- Fix the generation of user URLS.
- Pull code
- Load `/` check that it displays without any errors.

Fix homepage

---

templates/jaasai/kubernetes.html

- Sync the Kubernetes content with jujucharms.com
- Pull code
- Open http://0.0.0.0:8029/kubernetes
- Make sure the content matches https://jujucharms.com/kubernetes
- Fixes: #100.

Update /kubernetes content.

---

tests/jaasai/test_views.py
tests/store/test_views.py
webapp/store/views.py

- Generate the URLs in the tests so that if the URLs change the tests won't break.

Generate the static URLS in the view tests

---

tests/redirects/test_views.py
tests/store/test_views.py
webapp/app.py
webapp/redirects/views.py
webapp/store/views.py

- Move redirects to contained module.
- Add redirect to blog.
- Pull code
- Visit /blog
- You should get redirected to https://blog.ubuntu.com/topics/juju
- Fixes: #115.

Add blog redirect

---

templates/jaasai/experts.html

- Update the content on the /Experts page.
- Pull code
- Open http://0.0.0.0:8029/experts
- Check that the content matches http://jujucharms.com/experts
- Fixes: #109.

Update /experts content

---

templates/jaasai/community.html

- Update the community page to match jujucharms.com.
- Pull code
- Run `./run`
- Visit /community
- Check that the page matches what is on jujucharms.com (minus the blog post... that's coming).
- Fixes: #102.

Update community content

---

templates/jaasai/community/cards.html

- Fixed loading of cards on the cards page.
- Pull code
- Visit /community/cards
- The cards should load.
- Fixes: #118.

Fix /community/cards page

---

templates/jaasai/index.html
templates/shared/_spicule-card.html
templates/store/store.html

- Update the Spicule cards on the home and store pages.
- Move card to a shared template.
- Pull code
- Open /
- Check the Spicule card matches the one on http://jujucharms.com (you may need to refresh if the Tengu card is shown)
- Open /store
- Check the Spicule card matches the one on http://jujucharms.com/store (again, might need to refresh)
- Fixes: #110.

Update Spicule cards

---

static/sass/styles.scss
templates/jaasai/experts/spicule.html

- Update the bundles on /experts/spicule
- Link to the bundle details.
- Add a video link.
- Pull code
- Open /experts/spicule
- Check that the bundles listed are the same as on https://jujucharms.com/experts/spicule
- Fixes: #104.
- Fixes: #105.
- Fixes: #107.
- Fixes: #108.

Update Spicule bundles

---

templates/jaasai/experts/tengu.html

- Update bundle links on the /experts/tengu page.
- Pull code
- Open /experts/tengu
- Check that the bundle titles link to the bundles details.
- Check that the deploy buttons link to the GUI.
- Fixes: #141.

Update Tengu bundle links

---

templates/jaasai/support.html
tests/jaasai/test_views.py
webapp/jaasai/views.py

- Added a support page.
- Pull code
- Open /support
- The page should have three ways to get support.
- Fixes: #117.

Add support page

---

templates/jaasai/big-data.html

- Fix big data page cards.
- Add Anssr bundle.
- Pull code
- Open /big-data
- Check that the cards appear
- Check that the first bundle is "Anssr Data-engine"
- The content should match https://jujucharms.com/big-data
- Fixes: #140.

Update big-data page

---

static/sass/custom/_header.scss
static/sass/custom/_search-panel.scss
templates/shared/_navigation-search.html

Use Vanilla search box pattern
- Pull code
- Check the search box in the panel behaves as expected
Fixes #152

Use Vanilla search box pattern

---

.eslintrc.js
.gitignore
package.json
requirements.txt
static/js/src/blog-feed.js
templates/_layout.html
templates/jaasai/community.html
templates/shared/navigation.html
tests/jaasai/test_views.py
webapp/app.py
webapp/external_urls.py
webapp/jaasai/views.py
webapp/redirects/views.py
webpack.config.js

- Added a Webpack config so we can build multiple bundles.
- Display a blog feed on the Community page.
- Pull code
- Open /community
- Scroll down and you should see a couple of blog posts load onto the page.
- Fixes: #99.

Add blog feed

---

templates/_layout.html
templates/jaasai/big-data.html
templates/jaasai/community.html
templates/jaasai/community/partners.html
templates/jaasai/containers.html
templates/jaasai/how-it-works.html
templates/jaasai/index.html
templates/jaasai/jaas.html
templates/jaasai/kubernetes.html
templates/jaasai/openstack.html
templates/jaasai/support.html
templates/store/bundle-details.html
templates/store/charm-details.html
templates/store/store.html
webapp/app.py
webapp/experts.py
webapp/template_utils.py

- Added hashes to static URLs. Mostly the same as: https://github.com/canonical-websites/snapcraft.io/blob/83fe601711ac2437b70afa4d7b4dca7807183fd3/webapp/template_utils.py#L58
- Pull code
- Inspect some static files and check that they have an appended hash.
- Fixes: #164.

Add static hashing

---

static/robots.txt
templates/sitemaps/sitemap-base.xml
templates/sitemaps/sitemap-store.xml
templates/sitemaps/sitemap.xml
webapp/jaasai/views.py
webapp/store/models.py

- Added robots.txt
- Added sitemaps.
- Pull code
- Open /robots.txt you should see a basic robots.txt
- Open /sitemap.xml you should see the list of sitemaps.
- Open each sitemap, they should list the pages.
- Fixes: #157.

Add robots and sitemaps

---

webapp/external_urls.py

- Change the issues URL with the new GitHub team.
- Pull code
- Check in the footer that the "Report a bug on this site" link takes you to the "canonical-web-and-design" issues URL.

Update issues URL

---

static/sass/custom/_header.scss
templates/shared/navigation.html

Fix primary nav responsive bug
- Pull code
- Reduce screen width and observe the responsiveness of primary nav as 'About' and 'How it works' drop out of the menu

Fix primary nav responsive bug

---

static/sass/custom/_entities.scss
static/sass/custom/_search-results.scss
static/sass/custom/_series_tags.scss
static/sass/styles.scss
templates/store/_entity-header.html
templates/store/_search_row.html
templates/store/search.html
templates/store/user-details.html

Refactor styling of search results
- Pull code
- Search for a charm, e.g. 'Kibana'
- Observe updates styling od search results page
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/592

Refactor styling of search results

---

static/sass/styles.scss
templates/jaasai/how-it-works.html
templates/jaasai/index.html
templates/jaasai/jaas.html
templates/store/store.html

Tweak headings across the site
- Pull code
- Check markup changes against issue
Fixes #192

Tweak headings across the site

---

templates/shared/header.html

Add missing nav external links
- Pull code
- Verify nav links to external sources link as expected

Add missing nav external links

---

static/sass/styles.scss

Update active nav color
- Pull code
- Observe updated nav item highlight on hover
Fixes #221

Update active nav color

---

templates/jaasai/index.html

- Make the home hero card spacing match the design.
- Pull code
- Check that the home hero card spacing matches the design in #197.
Fixes: #197.

Fix home hero card spacing

---

templates/jaasai/how-it-works.html

- Fix the image alignment on the How It Works page.
- Pull code
- Open /how-it-works
- Check that the images and arrows are aligned and spaced like: https://user-images.githubusercontent.com/9105999/56803403-71d91000-681a-11e9-9bf1-a026c7dbe74e.png
- Fixes: #195.

How It Works alignment

---

templates/jaasai/index.html

- Add a high res version of the build it yourself image.
- Pull code
- In the "Or build it yourself" column the image should look good on high res screens
- Fixes: #235.

High res build it yourself image

---

package.json
static/js/src/app.js
static/sass/styles.scss
yarn.lock

Fixes #213
Add @canonical/cookie-policy
- Pull code
- Verify cookie policy appears
Fixes #213

Add cookie-policy

---

templates/_layout.html

Add Usabilla for user feedback
Check the demo for the 'Feedback' tag appearing on the right-hand side of the screen.

Add Usabilla for user feedback

---

templates/_layout.html
templates/jaasai/big-data.html
templates/jaasai/community/partners.html
templates/jaasai/containers.html
templates/jaasai/experts.html
templates/jaasai/experts/spicule.html
templates/jaasai/experts/tengu.html
templates/jaasai/how-it-works.html
templates/jaasai/index.html
templates/jaasai/jaas.html
templates/jaasai/kubernetes.html
templates/jaasai/openstack.html
templates/jaasai/support.html
templates/shared/header.html
templates/shared/search-panel.html

- Ran an accessibility audit use aXe dev tools
- Fixed semantic heading issues
- Fixed header nav issues
- Pull code
- Run accessibility audit with Lighhouse and verify a marked improvement on staging
Majority of the remaining issues are related to Global nav so I'll raise those issues there.

Accessibility improvements

---

webapp/store/models.py

Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/273
Fixes https://github.com/canonical-web-and-design/base-squad/issues/530
QA
--
`./run`, go to http://0.0.0.0:8029/search?requires=mysql, observe the conspicuous lack of server errors

Fix /search?requires= error

---

templates/jaasai/index.html

Removed exclamation mark from homepage hero text.
- Pull code
- Verify hero text (!) is removed
Fixes #282

Remove exclamation mark from hero index

---

templates/jaasai/index.html

Remove period from index hero
- Pull code
- Verify period removed

Remove period from index hero

---

.github/.stale.yml

Add config for “[Stale](https://github.com/probot/stale)” Github app
- Sanity check the config file

Added Stale Github config

---

templates/store/user-details.html

- To make the usernames consistent the profile username is no longer capitalised.
- Pull code
- Open /u/juju-solutions
- The username at the top should be hyphenated and lowercase.
- Fixes: #293.

Update username formatting on the profile

---

.circleci/config.yml
package.json

- Add circleci check for successful build
- Remove redundant `dir` flag from the postcss command
- Pull code
- check all tests on this PR pass
- Make CSS change locally and verify change

Fix build and correct postcss command

---

package.json
static/js/src/app.js
yarn.lock

Add Sentry JS tracking
- Pull code

Add Sentry JS tracking

---

templates/_layout.html

- Update the footer social icons to use the Vanilla defaults.
- Pull code
- Scroll to the footer, they icons should be larger and change colour on hover.
- Fixes: #284.

Update social icons

---

templates/jaasai/how-it-works.html
templates/jaasai/jaas.html

- Changed /jaas and /how-it-works pages to link to the GUI with "Your model".
- Pull code
- Open /jaas
- Check that the green button in the hero reads "Your models"
- Open /how-it-works
- Check that the green button just above the footer reads "Your models"
- Fixes: #315.

Update GUI links

---

requirements.txt
webapp/app.py
webapp/extensions.py
webapp/handlers.py

- use flask base extension and remove useless code
- Pull code
- make sure site works as usual

Use flask base and remove useless code

---

static/sass/custom/_patterns_strips.scss
static/sass/styles.scss
templates/_layout.html
templates/jaasai/index.html

Apply design to homepage design
- Pull code
- Check that the homepage content matches the [design](https://app.zeplin.io/project/5cf8ca699ee7bf1df9082012/screen/5cf8ca4478761e1b1ba07cbf)
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/325

Update the homepage design

---

static/sass/styles.scss
templates/store/store.html

Update the store page content
- Pull code
- Check that the content of the page matches [the design](https://app.zeplin.io/project/5cf8ca699ee7bf1df9082012/screen/5cf8ca4354e6df1dffcd7cfc)
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/327

Update the store page content

---

templates/jaasai/how-it-works.html

Update the deploy image on the how it works page
- Pull code
- Check the logos match the one in the issue
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/320

Update the deploy image on the how it works page

---

static/sass/custom/_patterns_strips.scss
static/sass/styles.scss
templates/jaasai/jaas.html

Update the about content design
- Pull code
- Open http://0.0.0.0:8029/jaas
- Check that the page content matches [the design](https://app.zeplin.io/project/5cf8ca699ee7bf1df9082012/screen/5cf8ca43b2b1882e1217d4ed)
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/328

Update the about content design

---

templates/jaasai/how-it-works.html

Update the how it works page design
- Pull code
- Check that the page matches [the design](https://app.zeplin.io/project/5cf8ca699ee7bf1df9082012/screen/5cf8ca44d6c75a1df329e444)
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/329

Update the how it works page design

---

static/sass/custom/_patterns_strips.scss
templates/store/_entity-header.html

Update the details hero background design.
- Pull code
- Open http://0.0.0.0:8029/mysql
- Check it matches [the design](https://app.zeplin.io/project/5cf8ca699ee7bf1df9082012/screen/5cfe111fdd0ff045f08a2da8)
- Go to http://0.0.0.0:8029/canonical-kubernetes/bundle/610
- Check it matches [the design](https://app.zeplin.io/project/5cf8ca699ee7bf1df9082012/screen/5cfe1941e700fa160e676688)
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/330
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/331
Bundle:
Charm:

Update details header design

---

templates/jaasai/index.html

Updated the "Why use Juju" images from the homepage.
- Pull code
- Scroll to the "Why use Juju" section and check the images look nice

Update the why use juju images

---

templates/jaasai/index.html

Update copy on index hero
- Pull code
- Check copy text in hero against issue - #316 
Fixes #316

Update copy on index hero

---

templates/jaasai/experts/tengu.html
webapp/experts.py

Tengu copy updates and update Growth Marketer details
- Pull code
- Open http://0.0.0.0:8029/experts/tengu
- Check all is well
Fixes #361, Fixes #362

Tengu copy updates

---

requirements.txt
templates/docs/_notification.html
templates/docs/base.html
templates/docs/commands.html
templates/docs/document.html
templates/docs/homepage.html
webapp/app.py
webapp/docs/views.py

Add first draft of docs
- Pull code
- Open http://0.0.0.0:8029/docs
- make sure docs work
- Open http://0.0.0.0:8029/docs
- Open http://0.0.0.0:8029/docs/commands
- those are custom pages

Add docs module

---

static/js/highlight.pack.js
static/sass/custom/_hljs.scss
static/sass/custom/_patterns_docs.scss
static/sass/styles.scss
templates/docs/base.html
templates/docs/commands.html
templates/docs/document.html
templates/docs/homepage.html
templates/shared/header.html

Add docs templates with navigation highlighting.
- Pull code
- Open http://0.0.0.0:8029/docs
- Check it looks good
- Check some pages are good and nav highlights
- Check /docs/commands page 
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/741
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/742
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/743
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/744
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/745

Add the template for docs

---

.circleci/config.yml
package.json

Added linkchecker CI checks 
Check that the linkchecker CI tasks on this PR passes
Related #360

Add linkchecker checks

---

templates/docs/base.html
templates/docs/homepage.html
templates/docs/search.html

Add the docs search template.
- Pull code
- Open http://0.0.0.0:8029/docs
- Search the docs
- Check the search results look ok

Add the docs search templates

---

redirects.yaml

Add redirect for /support/create to /support
- Pull code
- Open http://0.0.0.0:8029/support/create
- Verify you're redirected to http://0.0.0.0:8029/support
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/391

Add redirect for /support/create to /support

---

templates/404.html
templates/_layout.html
templates/jaasai/how-it-works.html
templates/jaasai/jaas.html
templates/jaasai/support.html
templates/store/search.html
templates/store/store.html
webapp/external_urls.py

Update links site-wide to reflect new docs structure
- Pull code
- Check all links still work
- Sanity check the code
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/386

Update links site wide to reflect new docs structure

---

static/sass/custom/_linkable-heading.scss
static/sass/styles.scss
templates/docs/document.html

Add linkable headings to docs
- Pull code
- Open http://0.0.0.0:8029/docs/installing
- Verify that headings are linkable on hover

Add linkable headings to docs

---

templates/store/_entity-header.html

Amend K8s entity header message link
- Pull code
- Check link
Fixes #407

Amend K8s entity header message link

---

templates/jaasai/experts/omnivector.html
webapp/experts.py
webapp/jaasai/views.py

Add Omnivector /experts page
- Pull code
- Open http://0.0.0.0:8029/experts/omnivector
- Cross-ref with [copy doc](https://docs.google.com/document/d/1h4o-HW5XIzm8YCjAbXRWhhJY5Sya0zaX0lDMPCWG-Kw/edit#heading=h.khiyagxplcjn)
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/884

Add Omnivector /experts page

---

static/js/tabpanel.js
static/sass/custom/_patterns_hero-tab.scss
static/sass/styles.scss
templates/jaasai/index.html

Add slider content to the homepage hero section
- Pull code
- Click the four sections in the hero and see the content changes
- The content matched [the design](https://app.zeplin.io/project/5cf8ca699ee7bf1df9082012/screen/5d0baf121c726159faaaaf36)

Add slider content to the homepage hero section

---

package.json

Update test script to use scss-lint script
- Pull code
- Verify all tests pass

Update test script to use scss-lint script

---

templates/docs/base.html

Make the titles dynamic in the documentation
- Got to the docs
- Click through the docs and see the title of the page changes with the heading of the page
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/433

Make the titles dynamic in the documentation

---

templates/_layout.html

The official Twitter account for the Juju project has recently changed. This PR updates the website to match.
- update links in _layout.html template
- Pull code
- [Add additional steps]
n/a
n/a

Update Juju Twitter account

---

requirements.txt
templates/jaasai/how-it-works.html

Add image module to /how-it-works
- Pull code
- Check images all load as expected
Fixes #439

Add image module to /how-it-works

---

static/sass/styles.scss
templates/shared/store-card/_card.html
templates/store/store.html

Add image-module to /store
- Pull code
- Check all images load correctly
Fixes #443

Add image module to /store

---

requirements.txt
templates/_layout.html
templates/jaasai/how-it-works.html
templates/jaasai/index.html
templates/shared/search-panel.html
templates/shared/store-card/_card.html
templates/store/store.html

Upgrade image template to v1.0.0
- Pull code
- Verify all images load as expected

Upgrade image template to v1.0.0

---

.circleci/config.yml

Include test-site check using the entrypoint script
- Make sure in this PR that CircleCI has a check called "test-site" and it pass

Include CircleCI test-site

---

static/sass/styles.scss
templates/jaasai/experts.html
templates/jaasai/experts/omnivector.html
webapp/experts.py

Update Omnivector details
- Pull code
- Open http://0.0.0.0:8029/experts
- Verify Omnivector text changes
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/913

Update Omnivector details

---

templates/docs/commands.html
webapp/docs/views.py

This reverts commit 616af0f74d881e9e44f726bd9e2b1638a5e792d2.

Revert "Remove the built-in commands"

---

package.json
static/js/modules/global-nav/global-nav.js

Copy the global-nav module to the project to share modules across discourse and other juju sites.
- Pull code
- Open http://0.0.0.0:8029/static/js/modules/global-nav/global-nav.js
- Check you see the matrix of js.

Copy the global-nav module to the project

---

Dockerfile

``` bash
DOCKER_BUILDKIT=1 docker build --tag jaasai .
docker run -ti -p 8666:80 jaasai
```
Go to http://localhost:8666, check it works a charm.

Use node 12 LTS, to match the run script

---

Dockerfile

``` bash
DOCKER_BUILDKIT=1 docker build --tag dashboard .
docker run -ti -p 8203:80 .
```

Fix dashboard build

---

package.json
yarn.lock

Remove redundant husky/pretty-quicks deps
- Pull code

Remove redundant husky/pretty-quicks deps

---

.circleci/config.yml
Dockerfile
entrypoint
requirements.txt

This reverts commit 84f7a971f6458bc3ed96fde3aa99c1dd98d6abcc.

Revert "Update to focal"

---

templates/jaasai/how-it-works.html
templates/jaasai/index.html
templates/jaasai/jaas.html

Link to /models
- Pull code
- Check links

Link to /models

---

.circleci/config.yml
.env
Dockerfile
entrypoint
requirements.txt

Fixes #528 
Fix run script issue.
- Pull code
- should work

Add secret key

---

templates/jaasai/index.html

Moved the period.
- Pull code
- Find that period!
Fixes #530

Move the period. Fixes: #530

---

static/js/src/search-filters.js

Null check the access to toggle controller
- Check this will resolve this error: https://sentry.is.canonical.com/canonical/jaas-ai/issues/9534/

Null check the access to toggle controller

---

templates/_layout.html

Fix social footer hover links
- Pull code
- Hover footer social link and verify they no longer have sneaky underline

Fix social footer hover links

---

static/js/tabpanel.js
templates/jaasai/index.html

Added tracking to the homepage carousel in the form of autoplay trigger and user click trigger.
- Go to the demo
- Waiting for the autoplay to switch to another panel and see if there is a GA event triggered
- Click on the next panel and see there is a GA event triggered
- Check there are no console errors
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1184

Add tracking to the carousel

---

static/js/src/modules/copy-snippet.js

Fix copy snippet bug
- Pull code
- Open http://0.0.0.0:8029/ceph
- Copy snippet on top right of the screen
- Verify it is now in your clipboard
Fixes #549

Fix copy snippet bug

---

deploy/site.yaml

Following this ticket: https://rt.admin.canonical.com/Ticket/Display.html?id=126016

Add domain jujulabs.ubuntu.com

---

static/sass/custom/_patterns_hero-tab.scss
templates/jaasai/index.html
tests/store/test_models.py
webapp/experts.py
webapp/jaasai/views.py
webapp/store/models.py
webapp/template_utils.py

- Fix jumping carousel on selected tab
- Fix some python files linting
- Pull code
- Click on a different carousel tab an see the orange line does not jump

Fix jumping carousel selected tab

---

templates/jaasai/how-it-works.html

Fix a typo on a link on how-it-works
- Check the code
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/600

Fix a typo on a link on how-it-works

---

templates/jaasai/how-it-works.html

Update charming get started docs link
- Check the link works
Fixes #625

Update charming get started docs link

---

requirements.txt
templates/jaasai/containers.html
templates/store/store.html

Fix a number of broken links across the site
- Check code, links work

Fix a number of broken links across the site

---

package.json
static/sass/custom/_patterns_hero-tab.scss
static/sass/custom/_search-panel.scss
static/sass/styles.scss
templates/jaasai/index.html
yarn.lock

Upgrade to Vanilla Framework 2.36.0
Blocked on #660
- It should look gud!
Fixes: https://github.com/canonical-web-and-design/app-squad/issues/268

Upgrade to Vanilla Framework 2.36.0

---

templates/404.html
templates/410.html
templates/500.html
templates/jaasai/community.html
templates/jaasai/how-it-works.html
templates/jaasai/index.html
templates/jaasai/jaas.html
templates/jaasai/kubernetes.html
templates/shared/header.html
templates/shared/search-panel.html
templates/store/store.html

Update all the store links across the site to point to charmhub. Some do not work but that will be picked up and checked with the linkchecker.
- Open the demo and check some changed links work
- Check the links look right
Fixes https://github.com/canonical-web-and-design/app-tribe/issues/513

Update charmhub links across the site

---

.github/workflows/pr.yaml

Fix dotrun github action
- Github check for dotrun needs to pass

Fix dotrun github action

---

webapp/store/views.py

Fix user entity URLs
- Go to https://jaas.ai/u/containers/aws-iam/115 and see it 500's
- Open the demo and go to /u/containers/aws-iam/115 and see if redirects

Fix user entity URLs

---

redirects.yaml

Add redirect for /store to charmhub
- Check this redirect works on the demo

Add redirect for store to charmhub

---

requirements.txt

Update flask-base to v1.0.3
- Check the code

Update flask-base to v1.0.3

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pr.yaml
.gitignore
Dockerfile
package.json
scripts/pull-latest-jaas-dashboard.sh
webapp/app.py

- Fix `docker build`
- Setup the jaas-dashboard so it works locally with `dotrun`
- Pull code
- Run `dotrun`
- Go to the dashboard
- Make sure that you are getting the dashboard rendered instead of a blank page
- Build the docker image:
```bash
DOCKER_BUILDKIT=1 docker build --progress=plain -t jaas-ai  .
```
- Run a container locally:
```bash
docker run -p 3000:80 --env-file=.env jaas-ai
```
- Again make sure that the dashboard is working locally

WD-990 - Fix the deployment

---

static/sass/styles.scss
templates/header.html
templates/index.html

- Removed max-width override of 72em to use Vanilla's default 80em
- Updated main title of the page with `p-heading--2` to match juju.is
- Forced some line-breaks for title's throughout the page.
- Visit demo
- Make sure things still look ok

Update width of site to match juju.is. Update logo. Update headers

---

templates/index.html

fix: mattermost link -> matrix

---

templates/_layout.html

[List of work items including drive-bys]
- Pull code
- Run `dotrun`
- [Add additional steps]
[List of links to issues/bugs and cards if needed]
[if relevant, include a screenshot]

Add webmaster tools verification code

---

.github/workflows/pr.yaml

Update dotrun install instructions in PR creation
Watch this PR checks pass

fix: update dotrun install in pr workflow

---

.github/workflows/pr.yaml

Updated pr.yml to install dotrun from pip with pinned requests version
- All checks should pass

ci: fix dotrun install

---

webapp/handlers.py

- Added security headers
- go to [HTTP header analyzer](https://dri.es/headers?url=https%3A%2F%2Fjaas-ai-769.demos.haus%2F)
- verify all the security headers exist.
- go to https://jaas-ai-769.demos.haus/
- Verify all the resources are shown correctly
- Verify there is no behavior change (such as a link doesnt open)
Fixes [#14417](https://warthogs.atlassian.net/browse/WD-14417)

feat: add missing csp

---

package.json
yarn.lock

Bump vanilla and sass versions

chore: bumps sass and vanilla

---

templates/index.html

Updated the homepage
- Go to https://jaas-ai-779.demos.haus/
- Compare to [the design](https://www.figma.com/design/PH98QJKmp4BBfFneN4ONsa/24.10-jaas.ai-copy-changes?node-id=2412-5547&t=N12zQFT7StsJsasn-0)
Fixes https://warthogs.atlassian.net/browse/WD-19427

chore: Update homepage

---

.github/workflows/deploy.yaml

Add missing tag to deploy workflow.

fix: add missing tag to deploy workflow
