canonical/jaas.ai

- templates/store/details.html
- webapp/store/views.py
Added `theblues` as a dep and start to use it to render the entity data.
- Run ./run
- Check a charm page (i.e. http://0.0.0.0:8029/wordpress) shows data
- Check a bundle page (http://0.0.0.0:8029/openstack-base) shows data
- Check a unnown entity (http://0.0.0.0:8029/blah) shows 404
Fixes https://github.com/ubuntudesign/juju-squad/issues/357
> Integrate theblues and load entity data

- requirements.txt
- templates/store/bundle-details.html
- templates/store/charm-details.html
- webapp/store/models.py
- webapp/store/views.py
Added the template and data for the charm details page.
- Go to /wordpress
- See that there is content
- Check that /haproxy/42 loads version 42
Fixes https://github.com/ubuntudesign/juju-squad/issues/348
> Add charm details page

- package.json
- yarn.lock
- Set the postcss option to not include the source maps and also removed cssnano. This reduces styles.css from 545kb to 175kb (locally).
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8029/](http://0.0.0.0:8029/)
- Open the network tab and see that styles.css is about 175kb. You could also open the file and check that it does not contain the sourcemaps.
> Remove cssnano. Don't include the source maps.

- templates/_layout.html
- Removed redundant IE comment from base template
- Added `preconnect` link to Google Analytics and Assets Server
- Run site with `./run`
- Check that when site loads, the links are in the head
> Preconnect to Assets Server and Google Analytics

- static/js/src/app.js
- static/js/src/modules/copy-snippet.js
- Bundle up JS util to add a copy button on entity details page as ES6 module
- View demo link below
- Navigate to `/nagios/trusty/7`
- Click the copy button next to the snippet on the top right
- Verify `cs:trusty/nagios-7` is copied to your system clipboard
> Bundle copy-snippet as ES6 module

- templates/jaasai/community.html
- templates/jaasai/community/partners.html
- templates/jaasai/openstack.html
- Removed mentions of OIL from /openstack, /community and /community/partners as the programme is dead
- Updated the copy doc
- Pull code
- Open http://0.0.0.0:8029/openstack, http://0.0.0.0:8029/community and http://0.0.0.0:8029/community/partners
- Compare to the copy docs:
- [/community](https://docs.google.com/document/d/1ZwmQ6XkUxLSfhlKSN-jhkcGpqRWx-h8EX_1VVE5-xd4/edit#)
- [/community/partners](https://docs.google.com/document/d/1oSB-4ARVBRqsMYE8R4lHsTGBvLh0FsogktpZ3rrYEGc/edit#)
- [/openstack](https://docs.google.com/document/d/1dwEVOARtzVXV4035xlxHfeTeaknv_iTy_3e_oE5SN1A/edit#)
Fixes #61
> Remove OIL program from the site

- static/sass/styles.scss
- Set the mobile nav breakpoint to handle the high number of nav items as well as the search box that is being added.
- Pull code
- Reduce your browser size until the content width starts to decrease. At this point the mobile nav should appear.
- Fixes: #66.
> Increase the nav breakpoint

- static/js/src/app.js
- Remove the login link from the global nav. 
- Pull code
- Check that there is no login link in the top right of the global nav.
- Fixes: #65.
> Don't show the login in the global nav

- templates/jaasai/index.html
- Correctly set the Spicule logo size on homepage
- Pull code
- Check that the size of the Spicule logo (in the JUJU EXPERT PARTNERS block) is the same size as on jujucharms.com.
- Fixes: #41.
> Set Spicule logo size on the homepage

- webapp/store/models.py
- Improve performance by only getting the files when needed (search and profile pages now take ~1 second instead of ~30 seconds).
- Pull code
- Do a search from the header. It should take about 1-2 seconds.
- Open a users profile. It should take about 1-2 seconds.
- View a charm. The readme should be visible and there should be a list of files on the right hand side.
- View a bundle. The readme should be visible.
> Improve search performance

- tests/store/test_views.py
- webapp/store/views.py
- Handle redirects of jujucharms.com style search urls.
- Pull code
- Do some searches using the URL format used on jujucharms.com e.g. `/q/k8s/demo?sort=-name&series=xenial`.
- You should be redirected to the new jaas.ai search URL format.
> Redirect searches

- static/sass/custom/_search-results.scss
- templates/store/charm-details.html
- templates/store/search.html
- tests/store/test_models.py
- webapp/store/models.py
- webapp/store/views.py
- Add functionality for sorting and filtering search results.
- Pull code
- Do a search. Use the controls to sort and filter the results.
- View a charm and click on a tag. You should see search results for that tag.
- View a charm and click on a relation in the Relations box on the right hand side. You should see search results for that relation.
- Fixes: #56.
- Fixes: #57.
- Fixes: #58.
> Add sorting and filtering

- templates/store/search.html
- Show the search count when there's not a query.
- Pull code
- Visit a search URL that doesn't have a search term e.g. `/search?tags=app-servers`.
- You should see the results count at the top.
> Show search count

- .circleci/config.yml
- .env
- package.json
- static/js/app/modal.js
- static/sass/custom/_modal.scss
- static/sass/styles.scss
- templates/jaasai/experts/spicule.html
- templates/jaasai/experts/thanks.html
- templates/shared/_spicule_lead-gen-form.html
- templates/store/bundle-details.html
- webapp/jaasai/views.py
Added lead generation form for Spicule
- Run feature branch
- Run `./run serve`
- View http://0.0.0.0:8029/experts/spicule
- Click 'Get in touch'
- This form still needs to be connected to Marketo so remains blocked.
> Lead generation modal for Spicule

- package.json
- tests/store/test_views.py
- webapp/store/views.py
- Restore the user entity URLs and add tests so we notice if these get broken/removed again in the future.
- Pull code
- View a user's profile. Click on some bundles and charms. They should load.
> Restore user urls

- templates/store/_entity-header.html
- templates/store/bundle-details.html
- templates/store/charm-details.html
- tests/store/test_models.py
- webapp/store/models.py
- webapp/store/views.py
- Normalise some model attributes to support the generic header.
- Add model tests.
- Pull code
- View some charms and bundles
- Check that the header details and description etc. appear as expected.
- Fixes: #90.
> Normalise model properties for templates

- webapp/app.py
- Fix a DeprecationWarning for ProxyFix.
- Pull code
- Run `./run test`
- Check that there is no DeprecationWarning for ProxyFix in your console.
> Fix ProxyFix DeprecationWarning.

- static/js/cli-typer.js
- Update relate command on the homepage.
- Pull code
- Check on the homepage that the command in the "Juju at your command" section displays "juju relate" not "juju add-relation" (you'll have to wait a while).
- Fixes: #98.
> Update relate command

- templates/500.html
- webapp/app.py
- Show a nice 500 page if there is a server error.
- Pull code
- In the .env file change `FLASK_DEBUG=true` to `FLASK_DEBUG=false`.
- In webapp/jaasai/views.py change the `index()` method to return `None`.
- Run `./run`
- Load /
- You should see the 500 page.
- Fixes: #127.
> Add 500 error page

- templates/jaasai/containers.html
- templates/jaasai/jaas.html
- templates/jaasai/kubernetes.html
- tests/store/test_models.py
- webapp/store/models.py
- Update references to CDK to be "The Charmed Distribution Of Kubernetes" instead of "Canonical Distribution".
- Pull code
- Visit /kubernetes /containers and /jaas
- They should have "Charmed Distribution" instead of "Canonical Distribution".
- Do a search for "Kubernetes".
- You should see "The Charmed Distribution Of Kubernetes" in the list.
- Click on it and check the bundle name is also "The Charmed Distribution Of Kubernetes".
- Fixes: #103 .
> Update the CDK name

- templates/jaasai/experts/spicule.html
- Update the about and skills section of /experts/spicule
- Pull code
- Open http://0.0.0.0:8029/experts/spicule
- Check that the About Us and Skills sections (at the bottom of the page) match jujucharms.com/experts/spicule
- Fixes: #111.
> Update the Spicule about section

- templates/jaasai/experts/spicule.html
- Update to the new Spicule logo on /experts/spicule
- Pull code
- Open /experts/spicule
- Check that the logo in the top right has a tag line (same as https://jujucharms.com/experts/spicule).
- Fixes: #142.
> Update Spicule logo on the Spicule page

- static/sass/custom/_header.scss
- templates/jaasai/jaas.html
- templates/shared/navigation.html
- templates/store/bundle-details.html
- templates/store/charm-details.html
- templates/store/search.html
- templates/store/store.html
Selected nav items should be highlighted
- Pull code
- Click on 'Store' in the primary nav and observe that active styling is persistent
- Click on 'About' in the primary nav and observe that active styling is persistent
Fixes #153
> Selected nav items should be highlighted

- static/sass/custom/_search-panel.scss
- templates/shared/search-panel.html
Remove hardcoded tags from search panel. 
- Pull code
- Open the search panel by clicking in the search box
- Observe that tags are no more
Fixes #148
> Remove hardcoded tags

- templates/shared/_navigation-search.html
Use ‘q’ instead of ‘name’ as search query identifier for reasons Robin [outlined in detail.](https://github.com/canonical-websites/jaas.ai/issues/159)
- Pull code
- Search for something in the header search box
- Confirm that the URL is `http://0.0.0.0:8029/search?q={YOUR_SEARCH_TERM}`
Fixes #159
> Use ‘q’ instead of ‘name’ as search query identifier

- templates/store/store.html
Remove hardcoded store tag counts
- Pull code
- Observe the counts next to tags are no more
> Remove hard coded store tag counts

- webapp/app.py
Update ‘Getting started’ link in primary nav
- Pull code
- click 'Getting started' in Global nav
- You should be directed to https://jujucharms.com/new/
Fixes https://github.com/ubuntudesign/juju-squad/issues/557
> Update ‘Getting started’ link in primary nav

- requirements.txt
- webapp/jaasai/views.py
- Add an in-memory cache for blog rss feed requests.
- Pull code
- Open /blog/feed and note how long it takes.
- Refresh the page, it should return immediately.
Fixes: #165.
> Cache the blog feed requests

- static/js/src/app.js
- static/sass/custom/_header.scss
- static/sass/styles.scss
Widen the max grid width to `72rem`.
- Pull code
- Check that the default row width is `72rem`
- See that the navigation matches
- Check the global-nav also matches the new max-width
- Check the pages look ok
Fixes #169 
Fixes #170
> Implement the wider grid in Vanilla

- templates/jaasai/how-it-works.html
- templates/shared/navigation.html
- Rename "Getting started" to "Get started" in the main nav.
- Add "How it works" item to the main nav.
- Pull code
- Open the home page.
- Check that there is a "How it works" item in the main nav.
- Check that there is an item named "Get started" (not "Getting started").
- Fixes: #594.
- Fixes: #595.
> Update header items

- templates/store/_entity-header.html
- webapp/store/models.py
- Get the revision info and correctly display it on charms and bundles.
- Pull code
- Open a charm or bundle
- Under the charm/bundle name it should say "Latest version" and have a number.
- Fixes: #85.
> Fix revision info

- templates/shared/_plan-card.html
- templates/store/_entity-header.html
- templates/store/bundle-details.html
- templates/store/charm-details.html
- tests/store/test_models.py
- webapp/store/models.py
- Show plans on supported charms (blues_browser had code for bundles as well, I did not add this as it doesn't seem to ever actually be able to be shown).
- Only show the expert card on supported charms.
- Pull code
- Open models.py and update the charmstore URL to use staging (https://api.staging.jujucharms.com/v5)
- open bundle-details.html
- move the `{% if context.entity.supported %}` block up out of the `{% if context.expert %}` block
- visit /u/hatch/estest/bundle/1
- you should see a "Managed solution" card on the right
- Fixes: #112.
- Fixes: #166.
> Add supported cards

- templates/store/_entity-header.html
Add ‘juju deploy’ to copy snippet in entity header
- Pull code
- Open http://0.0.0.0:8029/ntp/32
- Observe the copy snippet in the header says `juju deploy cs:ntp-32`
Fixes #190
> Add ‘juju deploy’ to copy snippet in entity header

- templates/jaasai/index.html
Add spacing to “Why use Juju” on index
- Pull code
- Scroll to "Why use Juju" 
- Verify sufficient spacing under large images
Fixes #198
> Add spacing to “Why use Juju” on index

- static/sass/custom/_homepage-hero-promo.scss
- templates/jaasai/index.html
- Add the new header background on the home page.
- Fix the home header diagram on mobile.
- Pull code
- Check that there is a grey background behind the header intro.
- Resize the page from desktop all the way down to mobile.
- The intro should look OK at all sizes and the diagram should eventually disappear.
- Fixes: https://github.com/canonical-web-and-design/juju-squad/issues/599.
- Fixes: https://github.com/canonical-web-and-design/juju-squad/issues/600
> Update home background and fix mobile

- tests/store/test_views.py
- webapp/store/models.py
- webapp/store/views.py
- Replace hyphens with spaces in searches.
- Attempt an entity search if there are no results.
- Pull code
- Do a search for "glance-simplestreams-sync" you should get a result.
- Do a search for "cs:~boucherv29/keepalived-19" and you should also get a result (you can also search for other user urls e.g. search for "/u/hatch/large-ghost/bundle/1").
- Do some normal searches and the results should be unchanged.
- Fixes: #130.
> Improve search quality

- templates/store/search.html
- tests/store/test_views.py
- webapp/store/views.py
- Generate entity filter URLs in the view.
- Pull code
- Do a search.
- Change some filters.
- Now switch between All/Charms/Bundles.
- You should get new results that maintain the other filters you selected.
- Fixes: #185.
> Improve entity filter URLs

- templates/shared/search-panel.html
- templates/store/store.html
- Some search URLs were using the old params.
- Pull code
- Open /store
- Click on a category, e.g. databases. The results should be limited to that term.
- Click in the search box and then click on one of the "Popular searches". It should return relevant results.
> Fix search strings

- .gitignore
- requirements.txt
- tests/jaasai/test_views.py
- webapp/jaasai/views.py
- Use the CachedSession as provided by https://github.com/canonical-web-and-design/http/.
- Pull code
- Open http://0.0.0.0:8029/blog/feed
- The page should take a few seconds
- Refresh. It should be very quick.
- Fixes: #180.
> Use the CachedSession from canonicalwebteam.http

- templates/jaasai/index.html
Update margins on homepage promos
- Pull code
- Check homepage promos on homepage across breakpoints
Fixes #200
> Update margins on homepage promos

- static/sass/custom/_search-results.scss
- templates/store/_entity-header.html
Add bottom margin to series tags in entity header
- Pull code
- Open http://0.0.0.0:8029/apache2/26
- Verify sufficent bottom margin on series tags
Fixes #189
> Add bottom margin to series tags in entity header

- templates/store/_search_row.html
- templates/store/bundle-details.html
- Replaced 'charm' reference with 'entity' reference
- Fix broken charm icons in search results
- Replaced broken default charm link with asset from the assets server
- Pull code
- Open https://staging.jaas.ai/search?type=charm
- Scroll all the way to the bottom and verify all charm icons load correctly
Fixes #193
> Fix broken charm icons in search results

- templates/store/store.html
Fix link to /containers from store
- Pull code
- Scroll to 'Container management'
- Click on 'Bundles' link
- Link should not 404
Fix #219
> Fix link to /containers from store

- tests/store/test_views.py
- webapp/store/views.py
- Include the filters in the second search.
- Pull code
- Open /search?q=kubernetes&series=centos7
- There should be no search results (because the filters are being applied).
- Fixes: #229.
> Fix search filters

- static/sass/custom/_search-results.scss
- Correctly wrap the series tags on the search results.
- Pull code
- Open /search?q=nova+hyperv
- The series should wrap within their column.
- Fixes: #223.
> Fix series wrapping on search results

- static/sass/styles.scss
- templates/jaasai/index.html
- Collapse the modelling steps on the homepage to two columns if there is room.
- Pull code
- Scroll to the "Choose", "Model", "Deploy" columns.
- Reduce your browser size, it should go from three columns to two colums, to one column.
- Fixes: #206.
> Collapse to two columns on homepage

- templates/store/store.html
- Update the "Container management" strip image and layout in the store.
- Pull code
- Open /store
- Scroll to the "Container management" section
- it should have the image like the design: https://user-images.githubusercontent.com/9105999/57071836-9417d580-6cd3-11e9-9abb-33356d812455.png
- Fixes: #227.
> Update the Container strip on the store.

- static/sass/styles.scss
- templates/jaasai/index.html
- Wrap the bundle names nicely on the homepage.
- Pull code
- Scroll down to the Deploy section
- Resize your browser down to mobile
- The bundle and charm titles should wrap nicely and stay vertically centred at every browser size.
- Fixes: #236.
> Home bundle name wrapping

- static/sass/custom/_entities.scss
- static/sass/custom/_search-results.scss
- templates/store/_entity-header.html
- templates/store/_search_row.html
- Top align the info in the search results table to match the new designs.
- Pull code
- Open /search
- The content should be top aligned in the cells
- Fixes: #242.
> Align search rows to the top

- static/sass/custom/_series_tags.scss
- Fix series label colours for centos and windows.
- Pull code
- Open /search?type=charm&series=centos7 and /search?type=charm&series=win2016
- The labels should be dark blue.
- Fixes: #249.
> Series labels colours

- static/sass/styles.scss
- Move the cookie policy scss import so that it doesn't override other Vanilla styles.
- Pull code
- Check that the paragraph spacing is not too small (see the screenshots in #250).
- Fixes: #250.
- Fixes: #252.
> Fix paragraph spacing

- static/sass/custom/_entities.scss
- static/sass/custom/_search-panel.scss
- templates/shared/search-panel.html
- templates/store/bundle-details.html
- Display icons as circles on the bundle details page and search dropdown.
- Pull code
- Open /u/marcoceppi/k8s-plus-nagios/bundle/0
- Check that the charm icons are circles in the "Bundle configuration" section on the right hand side.
- Click in the search box to open the search panel. All icons should be circles.
- Fixes: #248.
> Remove squircles

- static/sass/styles.scss
- templates/_layout.html
- templates/store/_search_row.html
Remove rogue underline from charm icons
- Pull code
- Open http://0.0.0.0:8029/search?type=bundle
- Hover over charm icons and verify no weird little underline appears
Fixes #254
> Remove rogue underline from charm icons

- templates/store/charm-details.html
There was a typo with the `bugs_url` in the charm details page causing them not to be shown.
`/keystone/299` should have a 'bug link' in the right column.
> bug_url to bugs_url

- static/js/src/search-icons.js
- static/sass/custom/_search-results.scss
- templates/store/_search_row.html
- templates/store/search.html
- templates/store/user-details.html
- tests/store/test_models.py
- webapp/store/models.py
- webpack.config.js
- Choose an icon for the bundle based on the name of the bundle and charms.
- Load a default icon if an icon 404s.
- Pull code
- Open /search?type=bundle
- Look through the list of icons and see if the chosen icon makes sense in most cases.
- The bundle icons should look like the one here: https://app.zeplin.io/project/5c5871a14e1897355935afb1/screen/5c6bc4e840eb10462ed01ed7
- Fixes: #253.
> Add bundle icons

- package.json
- yarn.lock
Bump global nav to 2.0.8
- Pull code
- Bask in those accessibility gains 💪🏻
> Bump global nav to 2.0.8

- templates/store/search.html
Search queries should be more than two characters or an error message is displayed in search results.
- Pull code
- Open http://0.0.0.0:8029/search?q=hu
- Verify an error noticiation is displayed
Fixes #247
> Search queries should be more than two characters

- static/robots.txt
- webapp/jaasai/views.py
- Make sitemap URL absolute
- Set response headers on sitemaps to be xml
- Remove Crawl-delay directive
- Pull code
- Open http://0.0.0.0:8029/sitemap.xml - should display as XML
- Open http://0.0.0.0:8029/sitemap-base.xml - should display as XML and list all pages
- Open http://0.0.0.0:8029/sitemap-store.xml - should display as XML and list all pages
Fixes #271
> Fix robots.txt file and serve sitemap filetypes as xml

- webapp/app.py
Add service name in logs to be able to play with logs
- Pull code
- make sure logs end with `service=jaas.ai`
> Add service name in logs

- static/sass/custom/_header.scss
- templates/shared/header.html
- Move "Your models" link to after the search box.
- Resize the search box.
- Pull code
- Resize your browser from desktop to mobile.
- The "Your models" link and search box should look good at all sizes.
- Fixes: #208.
> Move Your models link

- templates/store/bundle-details.html
- tests/store/test_models.py
- webapp/store/models.py
- yarn.lock
- Use the default charmstore URL.
- Fix visualisation spelling.
- Pull code
- Do a search. You should get results.
> Use default charmstore

- tests/store/test_models.py
- webapp/store/models.py
- Restore consistent list parsing (revert https://github.com/canonical-web-and-design/jaas.ai/pull/274/files).
- Add tests for fetching requires/provides.
- Pull code
- Open /search?provides=mysql
- The page should load
- Open /search?requires=mysql
- The page should load
- Fixes: #275.
> Add tests for fetching requires/provides

- templates/store/store.html
- Restore the container image width on the store page.
- Pull code
- Check that the container block image looks like the one on https://github.com/canonical-web-and-design/jaas.ai/issues/283
- Fixes: #283.
> Update container image width

- static/sass/styles.scss
Added padding to the right of the code snippet so you can see the entire value of the input when highlighting.
- Pull code
- Open http://0.0.0.0:8029/u/turku-charmers/turku-agent/3
- Highlight the content of the deploy CLI command
- Check you can see the entire command
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/308
> Fix clipboard icon cutting off the end of the CLI deploy command

- static/sass/custom/_homepage-hero-promo.scss
- templates/jaasai/index.html
- Fix video link at different screen sizes.
- Pull code
- Resize your screen from desktop through to mobile and watch the "Or watch the video" link (see https://github.com/canonical-web-and-design/jaas.ai/issues/292)
- The link should be spaced nicely when it wraps onto a new line.
- Fixes: #292.
> Fix video link spacing.

- static/sass/custom/_patterns_icons.scss
- static/sass/custom/_patterns_lists.scss
- static/sass/custom/_patterns_strips.scss
- static/sass/styles.scss
- templates/_layout.html
Added a new suru strip pattern and applied it to the footer of the site. Inverted a number of patterns namely the middot list and social icons.
- Pull code
- Scroll to the footer and check it matches [the design](https://app.zeplin.io/project/5cf8ca699ee7bf1df9082012/screen/5cfe111fdd0ff045f08a2da8)
- Check small screens works ok
- _The background pattern does not match the design as the asset is not easy to embed. I have used one from a takeover for now_ 
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/322
Desktop:
Small screen:
> Enhance the footer with a Suru pattern

- static/sass/custom/_patterns_strips.scss
- templates/_layout.html
- templates/jaasai/index.html
Added `is-slanted` as a state class to strips.
- Pull code
- Go to the homepage and check the section strip "Juju expert partners" is slanted at the bottom
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/324
> Add the is-slanted state to the strips pattern

- templates/jaasai/big-data.html
- templates/jaasai/community/cards.html
- templates/jaasai/openstack.html
- templates/store/bundle-details.html
- templates/store/charm-details.html
Bump juju-cards to 1.7.2
- Pull code
- Open http://0.0.0.0:8029/haproxy
- Check that the juju-card rendered nicely
- Check the logo appears in the footer of the card
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/255
> Update juju-cards to v1.7.2

- templates/_layout.html
- webapp/app.py
Add dynamic year variable to footer
- Pull code
- View footer and verify year on copyright notice is '2019'
Fixes #349
> Add dynamic year variable to footer

- templates/jaasai/experts/spicule.html
- templates/jaasai/experts/tengu.html
Fix spacing on /experts strap
- Pull code
- Open http://0.0.0.0:8029/experts/spicule & http://0.0.0.0:8029/experts/tengu
- check spacing on 'Join us' CTA button
Fixes #347
> Fix spacing on /experts strap

- templates/jaasai/how-it-works.html
Fix broken link on /how-it-works, removed redundant classes
- Pull code
- Scroll to ' Learn more about charms ›'
- Check link works
Fixes #360
> Fix broken link on /how-it-works

- webapp/store/models.py
Added a catch for missing readme and pass parsed is not available.
- Pull code
- Check out the problem charm: http://0.0.0.0:8029/u/canonical-bootstack/thruk-master/6
- Check a charm with a readme: http://0.0.0.0:8029/mysql
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/367
> Fix rendering of charms without readmes

- templates/store/_entity-header.html
- tests/store/test_models.py
- webapp/store/models.py
Fix Charmstore timeouts.
- Pull code
- `Latest revision` element should be gone but other than that, charm and bundle pages should remain functional.
- Timeouts are intermittent so we'll only see if this works once released and the logs show fewer timeouts.
Fixes #381
> Fix Charmstore timeouts

- .circleci/config.yml
- requirements.txt
- templates/docs/search.html
- webapp/docs/views.py
- Add search module to jaas.ai
- add basic template
Get hold of the "Custom Search API key" from the Google cloud API credentials page - if you don't have access to that page, ask @nottrobin/@tbille or someone for access.
Then, run the site with:
- `./run --env SEARCH_API_KEY={the-api-key}`
- http://0.0.0.0:8029/docs/search?q=test
- Should have a dictionnary full of results. Just needs templating now!
> Add search module for documentation

- templates/docs/homepage.html
Fix broken docs homepage links
- Pull code
- Open http://0.0.0.0:8029/docs
- Verify all the links in main content area no longer 404
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/389
> Fix broken docs homepage links

- requirements.txt
- webapp/docs/views.py
Upgrade to canonicalwebteam.discourse-docs v0.6.2 so we get a
/docs/sitemap.txt endpoint.
Change search to return results from jaas.ai/docs rather than
docs.jaas.ai.
QA
--
`./run --env SEARCH_API_KEY={thekey}`, go to `/docs/sitemap.txt` and see it in all its glory.
Go to `/docs/search`, search for things, see the results returned are at `jaas.ai/docs`.
> Sitemap and change search to jaas.ai/docs

- templates/store/_entity-header.html
Disable add-to-canvas button on kubernetes charms.
- Pull code
- Open http://0.0.0.0:8029/u/containers/coredns/0 and the button should not take you to the GUI.
- Open a charm and a bundle that are not kubernetes and their 'add-to-canvas' buttons should take you to the GUI.
Fixes #333
> Disable add-to-canvas button on kubernetes charms.

- static/js/src/modules/copy-snippet.js
Fix “Copy to clipboard” function in entity header
- Pull code
- Open http://0.0.0.0:8029/u/containers/coredns/0
- Click "Copy to clipboard" button
- Verify text is on clipboard
Fixes #400
> Fix “Copy to clipboard” function in entity header

- templates/jaasai/community.html
- templates/jaasai/index.html
- webapp/external_urls.py
Switch out 'Ask Ubuntu' links for Discourse links
- Pull code
- Check links to Discourse load as expected
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/387
> Switch out 'Ask Ubuntu' links for Discourse links

- package.json
- yarn.lock
Upgrade dependencies to resolve some of the vulnerable package warnings. None of these vulnerable packages are exposed to the client.
- Pull code
- Does it work as it should?
Fixes #402
> Upgrade dependencies.

- webapp/store/models.py
Increased charmstore request timeout from the default 3.05s to 5s.
- Pull code
- Use the site as normal - nothing should be broken by this change
- Deploy to staging and do the same
- Deploy to production and see the amount of noise on sentry decrease
At low usage times (UK AM) some pages (/u/openstack-charmers-next for example) take 2-3s to load the initial document, close to the 3.05s timeout threshold (obviously some of the time is taken up by other things), at peak usage times this will be worse.
I think it's better to take some time to show a user what they've asked for rather than show them nothing.
This is a short term solution to something more robust (https://github.com/canonical-web-and-design/jaas.ai/issues/7)
> increase charmstore timeout

- requirements.txt
- webapp/store/models.py
Swap out `gfm` for `py-gfm` to support backticks to represent code
- Pull code
- Open http://0.0.0.0:8029/u/openstack-charmers-next/nova-cloud-controller#configuration
- Scroll above the section linked above and verify that the large code black in the screenshot below is parsed as indented code.
Fixes #410
> Swap out gfm for py-gfm to support backticks

- templates/jaasai/experts/omnivector.html
- templates/jaasai/experts/spicule.html
- templates/jaasai/experts/tengu.html
- templates/shared/_expert_partner_cta_strip.html
- templates/shared/_omnivector_lead-gen-form.html
- templates/shared/_tengu_lead-gen-form.html
- templates/shared/contact-card/_card.html
- templates/shared/store-card/_random.html
- webapp/jaasai/views.py
- Add Omnivector & Tengu contact forms
- Add Omnivector rotating promo card to homepage in place of Tengu
- Abstract experts CTA strip into shared partial
- Pull code
- Check contact card at http://0.0.0.0:8029/experts/tengu
- Check contact card at http://0.0.0.0:8029/experts/omnivector
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/419,
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/418,
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/369
> Add Omnivector & Tengu contact forms

- templates/jaasai/index.html
Prevent initial hero image from lazy loading
- Pull code
- Very homepage index hero does not lazy load
> Prevent initial hero image from lazy loading

- templates/_layout.html
- Remove redundant Google fonts call
- Deferred non-critical scripts
- Remove redundant apple icons
- Reordered head tags
- Cross ref with:
- Pull code
- Verify all tests pass
> Audit site head to improve page render time

- requirements.txt
- webapp/app.py
- webapp/store/models.py
- Only configure markdown extension at start of the application (cleans a lot the logs)
- Configure the request session for better logs thanks to talisker
- Pull code
- check that you have `talisker.requests` logs now!
- try pages where markdown is rendered and make sure it looks as usual
> Track requests log

- templates/jaasai/index.html
Tweak JAAS logo on homepage
- Pull code
- Check logo on homepage loads correctly
Fixes #430
> Tweak JAAS logo on homepage

- templates/blog/_newsletter-signup-form.html
- The form was pointing at kubeflow news, I created a new marketo form and updated the id
- Pull code
- Open http://0.0.0.0:8029/case-studies
- See that the form goes to the correct marketo form
> Use correct marketo form id for case studies newsletter

- webapp/docs/views.py
Fix https://sentry.is.canonical.com/canonical/jaas-ai/issues/4330/
The /docs/commands page was 500.
- Pull code
- Open http://0.0.0.0:8029/docs/commands
- this should work and not 500
> Add title to command page

- static/sass/custom/_patterns_docs.scss
From Usabilia report - 
_"I am using google chrome on iPad. In landscape mode there is no text associated with any of the TOC entries. In portrait mode, there is text but no TOC."_
The mobile menu was appearing as 100% width until the screen width was greater than `$breakpoint-large` which is `1680px`. This change corrects this so that the mobile width is only 100% until the screen width is greater than `768px`.
- Pull code
- Test `/docs/` by emulating an iPad in landscape mode and verify that sidebar and content are side-by-side.. (and on all devices with screen width greater than 768px)
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/482
> Reduce navigation breakpoint for docs layout

- templates/store/search.html
- webapp/store/views.py
Stop stripping dashes from a search query.
- Pull code
- Search for `td-agent` and check it returns the charm
- Check production does not return anything
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/491
> Stop the search striping dash

- .dockerignore
- Dockerfile
- package.json
Switch over to multistage build to fix the problem with node version in the build for production.
``` bash
./run clean  # To prove we don't need it
DOCKER_BUILDKIT=1 docker build --tag jaasai --build-arg BUILD_ID=sdfgds .
docker run -ti -p 8666:80 jaasai
```
Go to http://localhost:8666, check it works a charm.
Then, do:
``` bash
$ curl -I http://localhost:8666
X-VCS-Revision: sdfgds
```
^ Check you see the `BUILD_ID` there.
> Multistage build

- Dockerfile
- webapp/app.py
At present I'm only adding the jaas-dashboard site files within the `Dockerfile`, so they'll only be included in the production build.
I hope this is okay for now. If we want to be able to test the dashboard in-place with `./run` later we can add that capability.
QA
--
``` bash
DOCKER_BUILDKIT=1 docker build --tag dashboard .
docker run -ti -p 8203:80 dashboard
```
Now go to http://localhost:8203, check the site works fine.
Then go to http://localhost:8203/models, check the dashboard works as expected.
> Integrate dashboard

- Dockerfile
The jaas-dashboard clone was being cached in subsequent builds, so we
weren't pulling in the latest version of the repo for every build.
This should fix that. @jkfran found
[this technique](https://stackoverflow.com/questions/36996046/how-to-prevent-dockerfile-caching-git-clone)
of using `ADD` to query https://api.github.com/,
but unfortunately it didn't work for me because I kept getting the error
"invalid not-modified ETag" from GitHub. This
[should have been fixed](https://github.com/moby/buildkit/issues/905)
but the fix doesn't seem to have made its way into latest docker-ce yet.
So at some point in the future we could use this solution.
For the time being I've instead used https://httpbin.org/uuid to create
a cache-busting line in the `Dockerfile` just above the git clone.
This is …
> Avoid caching jaas-dashboard clone

- .dockerignore
- Dockerfile
Improve on PR #500 by using the local `.git/refs/heads/master`
file instead of `httpbin` for cache-busting.
This makes things a lot more efficient as well as not requiring access
to httpbin.
QA
--
Use QA steps from #500
> Improve cache-busting for jaas-dashboard clone

- redirects.yaml
Add redirect from /get-started to the docs page.
- Pull code
- Open http://0.0.0.0:8029/get-started
- Check it loads the get started docs page
> Add redirect to get-started page

- webapp/jaasai/views.py
Create explicit route to serve favicon from root
- Pull code
- Check you can serve http://0.0.0.0:8029/robots.txt
- Check you can serve http://0.0.0.0:8029/favicon.ico
> Create explicit route to serve favicon from root

- requirements.txt
Temporary fix for flask testing:
Toto explanations:
```
well this is an issue https://github.com/jarus/flask-testing/pull/141
flask doens't pin werkzeurg
werkzeurg just made and upgrade to v1 and now libraries that depend on flask and some features of wekzeurg are breaking
the PR above is an example of stuff breaking and we are using it on snap and jaas (and maybe other websites) this means that testing will break and block ...
```
Make sure tests pass now
> Pin werkzeurg to 0.16.1

- webapp/app.py
JAAS Dashboard requires https://jaas.ai/config.js and is currently broken as it is 404ing. 
This PR whitelists that route in the flask app and updates the Docker script to copy it across from the jaas-dashboard root to jaas.ai root.
I have no way to test this locally so all eyes on please.
Build and run the docker image:
``` bash
DOCKER_BUILDKIT=1 docker build --tag jaas.ai .
docker run -ti -p 8555:80 jaas.ai
```
Once the server is running from the built image, go to http://localhost:8555/models and check it more-or-less works.
> Whitelist config.js route

- templates/store/bundle-details.html
This commit fixes the broken "ref" attribute to "href".
- Pull code
- Visit a bundle
- Check that you're able to click the link on the embed widget
> Fix broken <a> tags to /community/cards

- templates/jaasai/index.html
- templates/shared/header.html
- Add release banner
- Change models link in nav to /models
Note: blocked for now on Discourse link
- Pull code
- View release banner
- Check that "Your models" link opens dashboard
Related: https://github.com/canonical-web-and-design/juju-squad/issues/1175
> Release banner

- templates/_layout.html
- templates/jaasai/big-data.html
- templates/jaasai/community.html
- templates/jaasai/containers.html
- templates/jaasai/index.html
- templates/jaasai/jaas.html
- templates/jaasai/kubernetes.html
- templates/jaasai/openstack.html
- webapp/external_urls.py
- webapp/tutorials/views.py
- Bumped the image-template module
- Add images modules to supplementary pages
- Corrected any old Discourse links
- Pull code
- Open http://0.0.0.0:8029/about
- Open http://0.0.0.0:8029/big-data
- Open http://0.0.0.0:8029/kubernetes
- Open http://0.0.0.0:8029/community
- Open http://0.0.0.0:8029/containers
- Open http://0.0.0.0:8029/openstack
- Check all images load as expected
> Add images modules to supplementary pages

- templates/_layout.html
- templates/store/bundle-details.html
- templates/store/charm-details.html
- tests/store/test_models.py
- webapp/store/models.py
Add canonical rel link to charm and bundle details pages
- Pull code
- Open http://0.0.0.0:8029/nagios
- Check source. The canonical link should be the same
- Go to /nagios/14 and check the canonical link is to the main one.
- Check a bundle (/canonical-kubernetes/500) works too.
Fixes #561
> Add Canonical URL to entity templates

- tests/store/test_models.py
- webapp/store/models.py
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/487
Replaced parser with `PartialGithubFlavoredMarkdownExtension` as suggested in [this comment ](https://github.com/canonical-web-and-design/jaas.ai/issues/487#issuecomment-577870914)
- Pull code
- Open http://0.0.0.0:8029/nova-compute
- test different charm pages to make sure that the content seems to be correctly displayed.
> Fix issue with markdown parser

- requirements.txt
- templates/blog/_case-study-card.html
Update module version and make study cases use the rendered images provided by the module.
Click on the demo link. Browse to `/case-studies`.
Check that thumbnails are ok. Click on some articles, check the images are fine:
The urls of the images should be pointing to `ubuntu.com/wp-content` not `admin.insights.ubuntu.com/wp-content`
The cloudinary service should be enabled for both thumbnails and article images.
> Update blog module version

- templates/jaasai/big-data.html
Fix squashed image on big data page by removing fixed height
- Pull code
- Open http://0.0.0.0:8029/big-data
- Make sure the image is not squashed
**No**
**Yes**
> Remove fixed height

- templates/jaasai/big-data.html
Remove dead link from /big-data
- Pull code
- Open http://0.0.0.0:8029/big-data
- Scroll to the bottom and verify the link has gone
fixes #547
> Remove dead link from /big-data

- requirements.txt
- webapp/app.py
Fix blog article thumbnails.
Go to: https://jaas.ai/case-studies
Check the thumbnails, you will notice they do not have the same size.
Go to: https://jaas-ai-588.demos.haus
Check the thumbnails, you will notice they all have the same size(354x180) and cover the whole width of the block.
Part of: https://github.com/canonical-web-and-design/canonicalwebteam.blog/pull/153
Before:
After:
> Set width and height to thumbnails

- templates/_layout.html
Add a link to manage the cookie settings in the footer
- Pull code
- Scroll to the footer and click the link
- Check the cookie policy opens again
> Add a link to manage the cookie settings in the footer

- templates/store/search.html
Add focal filter to charm store
- Pull code
- Open http://0.0.0.0:8029/search?q=databases
- Click filter dropdown
- Select 'Focal' and see that all results support 'Focal'
Fixes #580
> Add focal filter to charm store

- static/js/src/app.js
- static/js/src/latest-news.js
- templates/_layout.html
- templates/jaasai/community.html
- webpack.config.entry.js
Resolve error in the console where latest news lib was running on all pages.
- Pull code
- Ensure no console errors.
Fixes #576
> Resolve console errors

- requirements.txt
- templates/store/charm-details.html
- webapp/store/views.py
- Set canonical url to charmhub.io for charms
- `dotrun`
- http://0.0.0.0:8029/grafana
- If the charm exists on charmhub then don't show the canonical url
- otherwise show canonical url to charmhub
- Check that the canonical url is charmhub.io
Before redirecting the store we can start SEOing the charm pages to charmhub.io/<charmname>
> Set canonical URL to charmhub.io for charms

- templates/jaasai/jaas.html
- Fixed indentation in “Start modelling” section
- Pull code
- Open http://0.0.0.0:8029/jaas
- Scroll to “Getting started” step 3
Fixes #601
> Fixes indentation in “Start modelling” section

- requirements.txt
- tests/jaasai/test_views.py
- webapp/jaasai/views.py
Use talisker.requests session instead of canonicalwebteam.http.CachedSession
- dotrun and check `/blog/feeds` works.
Potentially fixes #606
> Remove canonicalwebateam.http and use talisker.requests session

- templates/jaasai/containers.html
- templates/jaasai/how-it-works.html
- templates/jaasai/index.html
- templates/jaasai/jaas.html
- templates/jaasai/kubernetes.html
- templates/shared/search-panel.html
- tests/store/test_models.py
- webapp/store/models.py
convert canonical-kubernetes to charmed-kubernetes naming
- Pull code
- Look for any instances of `canonical-kubernetes` and that the updated sections with `charmed-kubernetes` still work as expected.
Fixes #617
> Convert canonical-kubernetes to charmed-kubernetes naming

- static/js/src/app.js
Add hiring link to the global nav
- `dotrun`
-  http://0.0.0.0:8029
- Make sure global nav has a we're hiring link to the juju.is careers page
> Add hiring link to global nav

- templates/jaasai/experts/omnivector.html
- templates/jaasai/experts/spicule.html
- templates/jaasai/experts/tengu.html
- templates/jaasai/jaas.html
- templates/jaasai/kubernetes.html
- templates/shared/_plan-card.html
- templates/store/_entity-header.html
Remove the links to the GUI across the site
- Open the demo
- Go to the different expert pages and see there is no deploy button and the page still works
- Go to an entity page and check there is no deploy to model button
> Remove the links to the GUI

- .prettierignore
- static/sass/styles.scss
- templates/jaasai/index.html
- templates/store/store.html
Add a notification to indicate the upcoming switch to charmhub.
jaas.ai is using an old version of Vanilla so the notification looks a bit different than the design but I made an attempt to make it as close as possible.
Look at / and /store page for the notification.
Fixes: https://github.com/canonical-web-and-design/app-squad/issues/265
> Add notification about the upcoming switch to charmhub.

- requirements.txt
Bump juju-bundlelib v0.5.7
- Open the demo
- Go to /search?type=bundle
- Go to /mlflow
Fixes https://github.com/canonical-web-and-design/jaas.ai/issues/667
> Bump juju-bundlelib v0.5.7

- templates/store/charm-details.html
- templates/store/search.html
- templates/store/store.html
- webapp/store/views.py
Add canonical links for user charms and bundles and the store page.
Removed the look up for existence as we will be cutting over to redirect to charmhub shortly.
- Go to /?q=foo and check the source contains `<link rel="canonical" href="https://charmhub.io?q=foo" />`
- Go to /u/canonical-sysadmins/wordpress-services/2 and check the source contains `<link rel="canonical" href="https://charmhub.io/canonical-sysadmins-wordpress-services" />`
- Go to /store and check the source contains `<link rel="canonical" href="https://charmhub.io" />`
- Go to /nagios and see the course contains `<link rel="canonical" href="https://charmhub.io/nagios" />`
Fixes https://github.com/canonical-web-and-design/app-tribe/issues/510
> Add canonical links to store pages

- Dockerfile
- package.json
- yarn.lock
- Update node version from 12 -> 16
- Add a line to disable pip version check
- Pull code
- [Add additional steps]
This should unblock the renovate PRs
[if relevant, include a screenshot]
> Update Dockerfile, primarily for NodeJS 12 -> 16

- templates/jaasai/how-it-works.html
- webapp/app.py
- fix typo in "how it works" section: "such **us**" -> "such as"
> fix minor typo in 'how it works' section

- templates/jaasai/how-it-works.html
* Updated FAQ links to Juju documentation
- Pull code
- Run `dotrun`
- Verified that each FAQ link leads to a valid documentation page
Closes #730
> Fix broken links to Juju documentation

- templates/header.html
- Update navigation from a Mattermost link to Matrix
- Visit the demo
- Check the "Community" navigation dropdown has a link to matrix.
> fix: update mattermost link to matrix

- templates/header.html
- Add Juju middle pages on Jaas.ai
- Go to https://jaas-ai-752.demos.haus/
- Check if you can access `How Juju Works` from the main navigation
Fixes #https://warthogs.atlassian.net/browse/WD-11205
> Add Juju middle pages on Jaas.ai

- templates/index.html
- Update the screenshots to match the latest dashboard.
- Pull code
- Run `dotrun`
- Scroll down to the dashboard screenshots.
- Check that they match the new grey dashboard.
[List of links to issues/bugs and cards if needed]
> feat: update screenshots to latest dashboard

- webapp/handlers.py
- Added security headers
- go to [HTTP header analyzer](https://dri.es/headers?url=https%3A%2F%2Fjaas-ai-768.demos.haus%2F)
- verify all the security headers exist.
- go to https://jaas-ai-768.demos.haus/
- Verify all the resources are shown correctly
- Verify there is no behavior change (such as a link doesnt open)
Fixes [#14417](https://warthogs.atlassian.net/browse/WD-14417)
> feat: Add security headers

- templates/header.html
Update "Docs" in nav bar to point to https://canonical-jaas-documentation.readthedocs-hosted.com/en/latest/ rather than have a dropdown.
- Pull code
- Run `dotrun`
- Ensure "Docs" link in nav bar is as expected.
> update nav bar docs link

- templates/header.html
Remove the "How Juju Works", "Community", and "Blog" buttons.
- Pull code
- Run `dotrun`
- Check links have been removed from nav bar
> remove unnecessary nav bar links

- templates/index.html
- Company and Job title fields are now mandatory
- drive by: added missing "is-required" class on required input's labels
- View the site in your web browser at: https://jaas-ai-782.demos.haus/
- Click the green "Contact us" button
- Verify the job title field is mandatory
Bonus points: try to submit the form to make sure it works.
Fixes #[WD-19677](https://warthogs.atlassian.net/browse/WD-19677)
[WD-19677]: https://warthogs.atlassian.net/browse/WD-19677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Mandatory job title field on jaas.ai contact forms

- templates/index.html
- update JAAS controller screenshot to have correct percentages
- Pull code
- Run `dotrun`
- Scroll to "Enhanced control and visibility for your Juju deployment", and ensure that the "Onboard controllers and manage access" item in the carousel fits in with the other images
Replaces [previous asset](https://assets.ubuntu.com/v1/2f434d5d-jaas-controllers.png) with bad percentages, with [updated asset](https://assets.ubuntu.com/v1/d54720f1-jaas-controllers.png) which displays correct percentages. This screenshot was produced using a version of Juju Dashboard with the fix from https://github.com/canonical/juju-dashboard/pull/1979.
(might have to zoom in to see the percentages)
> fix: update JAAS controller screenshot to remove patched UI bug

- .github/workflows/deploy.yaml
Fix deploy Github Action error with incorrect variable name (there were some changes in webteam-devops repository).
This Github Action run successfully in staging: https://github.com/canonical/jaas.ai/actions/runs/15920882160
> fix: wrong environment_url after changes in webteam-devops

- templates/header.html
JAAS docs have just moved to https://documentation.ubuntu.com/jaas . This PR updates the link on jaas.ai.
- Pull code
- Run `dotrun`
- [Add additional steps]
[List of links to issues/bugs and cards if needed]
[if relevant, include a screenshot]
> docs: update jaas docs link
